#!/bin/bash

#alias hbase=/home/vagrant/hbase-0.94.6.1/bin/hbase
export HBASE_HOME="/home/vagrant/hbase-0.94.11/"
alias hbase=$HBASE_HOME/bin/hbase #.tar.gz
alias start-hbase="sudo $HBASE_HOME/bin/start-hbase.sh"
alias stop-hbase="sudo $HBASE_HOME/bin/stop-hbase.sh"
